import type { Report } from '../types'

const now = Date.now()

export const buildMockReports = (): Report[] => [
  {
    id: crypto.randomUUID(),
    title: '路灯不亮 - 望京SOHO东侧',
    description: '整段道路照明不足，夜间行人视线差。',
    categoryId: 1,
    categoryName: 'Street Light',
    latitude: 39.9921,
    longitude: 116.4749,
    address: '北京市朝阳区望京SOHO东侧',
    status: 'pending',
    createdAt: new Date(now - 1000 * 60 * 90).toISOString(),
    synced: true,
    photos: [],
  },
  {
    id: crypto.randomUUID(),
    title: '道路坑洞 - 北苑路辅路',
    description: '坑洞较深，电动车经过有安全隐患。',
    categoryId: 2,
    categoryName: 'Road Damage',
    latitude: 40.0069,
    longitude: 116.4074,
    address: '北京市朝阳区北苑路辅路',
    status: 'processing',
    createdAt: new Date(now - 1000 * 60 * 210).toISOString(),
    synced: true,
    photos: [],
  },
  {
    id: crypto.randomUUID(),
    title: '垃圾桶满溢 - 奥林匹克森林公园南门',
    description: '周末人流较大，垃圾桶已满且有异味。',
    categoryId: 3,
    categoryName: 'Garbage',
    latitude: 40.0204,
    longitude: 116.3967,
    address: '北京市朝阳区奥林匹克森林公园南门',
    status: 'resolved',
    createdAt: new Date(now - 1000 * 60 * 360).toISOString(),
    synced: true,
    photos: [],
  },
  {
    id: crypto.randomUUID(),
    title: '交通标识倾斜 - 安立路口',
    description: '标识牌倾斜明显，建议尽快加固。',
    categoryId: 4,
    categoryName: 'Traffic Sign',
    latitude: 40.0038,
    longitude: 116.4089,
    address: '北京市朝阳区安立路口',
    status: 'pending',
    createdAt: new Date(now - 1000 * 60 * 35).toISOString(),
    synced: false,
    photos: [],
  },
  {
    id: crypto.randomUUID(),
    title: '路灯闪烁 - 酒仙桥路',
    description: '路灯间歇性闪烁，可能线路老化。',
    categoryId: 1,
    categoryName: 'Street Light',
    latitude: 39.9808,
    longitude: 116.5002,
    address: '北京市朝阳区酒仙桥路',
    status: 'processing',
    createdAt: new Date(now - 1000 * 60 * 15).toISOString(),
    synced: true,
    photos: [],
  },
]
